/*
  Generated by scripts/precompute.mjs — do not edit by hand.

  200,000 random n x n games at each size, seeded with
  mulberry32(12345 + n), counting cells that survive the dots-and-circles test.
  Payoffs are independent uniforms, so ties have probability zero and every
  game is generic.

  `p[k]` is the share of games with exactly k pure equilibria, with k = 5
  meaning "5 or more".
*/
export const TRIALS = 200000;
export const COUNT_BY_SIZE = [
  {
    "n": 2,
    "mean": 1.001155,
    "p": [
      0.124605,
      0.749635,
      0.12576,
      0,
      0,
      0
    ]
  },
  {
    "n": 3,
    "mean": 1.00173,
    "p": [
      0.21358,
      0.579535,
      0.19846,
      0.008425,
      0,
      0
    ]
  },
  {
    "n": 4,
    "mean": 0.99863,
    "p": [
      0.258335,
      0.50758,
      0.21164,
      0.02201,
      0.000435,
      0
    ]
  },
  {
    "n": 5,
    "mean": 1.001785,
    "p": [
      0.282495,
      0.468575,
      0.21496,
      0.0326,
      0.00136,
      0.00001
    ]
  },
  {
    "n": 10,
    "mean": 1.00206,
    "p": [
      0.327755,
      0.410495,
      0.20218,
      0.051775,
      0.00713,
      0.000665
    ]
  },
  {
    "n": 25,
    "mean": 1.00298,
    "p": [
      0.351765,
      0.38395,
      0.19053,
      0.05932,
      0.012365,
      0.00207
    ]
  },
  {
    "n": 100,
    "mean": 1.002465,
    "p": [
      0.363705,
      0.37083,
      0.18689,
      0.060455,
      0.01479,
      0.00333
    ]
  }
];
