/*
  GENERATED by scripts/precompute.mjs - do not edit.

  Produced by the same modules the page imports (src/gbdt.js, src/binning.js,
  src/datasets.js). verify/check-numbers.mjs re-runs every fit in here and
  fails if any number has moved, so this file cannot go stale unnoticed.
*/
export default {
 "config": {
  "N_TRAIN": 6000,
  "N_TEST": 3000,
  "maxBin": 255,
  "numLeaves": 31,
  "minDataInLeaf": 20,
  "lambda": 1,
  "gamma": 0,
  "learningRate": 0.1,
  "numTrees": 60,
  "subtract": true,
  "minDataInBin": 3
 },
 "BIN_SETTINGS": [
  2,
  4,
  8,
  16,
  32,
  64,
  128,
  255
 ],
 "LEAF_FLOORS": [
  5,
  20,
  80,
  250
 ],
 "FLOOR_BINS": [
  8,
  16,
  32,
  64,
  128,
  255
 ],
 "exact": {
  "train": 3.664070250530766,
  "test": 4.957024936342493,
  "gainEvals": 7628403,
  "rowTouches": 10750184,
  "histBuilds": 0,
  "histSubtracts": 0,
  "nBins": null,
  "curve": [
   {
    "round": 0,
    "train": 13.9026,
    "test": 14.5194
   },
   {
    "round": 1,
    "train": 12.7627,
    "test": 13.3968
   },
   {
    "round": 2,
    "train": 11.7517,
    "test": 12.4031
   },
   {
    "round": 3,
    "train": 10.8423,
    "test": 11.5067
   },
   {
    "round": 4,
    "train": 10.0341,
    "test": 10.7079
   },
   {
    "round": 5,
    "train": 9.3252,
    "test": 10.0079
   },
   {
    "round": 6,
    "train": 8.6958,
    "test": 9.3913
   },
   {
    "round": 7,
    "train": 8.1409,
    "test": 8.8488
   },
   {
    "round": 8,
    "train": 7.6443,
    "test": 8.3689
   },
   {
    "round": 9,
    "train": 7.2102,
    "test": 7.95
   },
   {
    "round": 10,
    "train": 6.8191,
    "test": 7.5842
   },
   {
    "round": 11,
    "train": 6.4775,
    "test": 7.2641
   },
   {
    "round": 12,
    "train": 6.1737,
    "test": 6.9786
   },
   {
    "round": 13,
    "train": 5.9099,
    "test": 6.7405
   },
   {
    "round": 14,
    "train": 5.6742,
    "test": 6.5193
   },
   {
    "round": 15,
    "train": 5.4661,
    "test": 6.3389
   },
   {
    "round": 16,
    "train": 5.2878,
    "test": 6.175
   },
   {
    "round": 17,
    "train": 5.1242,
    "test": 6.026
   },
   {
    "round": 18,
    "train": 4.9812,
    "test": 5.8997
   },
   {
    "round": 19,
    "train": 4.8489,
    "test": 5.7796
   },
   {
    "round": 20,
    "train": 4.74,
    "test": 5.6884
   },
   {
    "round": 21,
    "train": 4.6312,
    "test": 5.5958
   },
   {
    "round": 22,
    "train": 4.5389,
    "test": 5.5205
   },
   {
    "round": 23,
    "train": 4.4588,
    "test": 5.4505
   },
   {
    "round": 24,
    "train": 4.3857,
    "test": 5.3914
   },
   {
    "round": 25,
    "train": 4.3253,
    "test": 5.3436
   },
   {
    "round": 26,
    "train": 4.2654,
    "test": 5.2989
   },
   {
    "round": 27,
    "train": 4.2112,
    "test": 5.2568
   },
   {
    "round": 28,
    "train": 4.1625,
    "test": 5.2174
   },
   {
    "round": 29,
    "train": 4.122,
    "test": 5.1904
   },
   {
    "round": 30,
    "train": 4.0842,
    "test": 5.1591
   },
   {
    "round": 31,
    "train": 4.0512,
    "test": 5.1332
   },
   {
    "round": 32,
    "train": 4.0208,
    "test": 5.1097
   },
   {
    "round": 33,
    "train": 3.993,
    "test": 5.0887
   },
   {
    "round": 34,
    "train": 3.9709,
    "test": 5.0737
   },
   {
    "round": 35,
    "train": 3.9482,
    "test": 5.0608
   },
   {
    "round": 36,
    "train": 3.9275,
    "test": 5.0468
   },
   {
    "round": 37,
    "train": 3.9072,
    "test": 5.0339
   },
   {
    "round": 38,
    "train": 3.8895,
    "test": 5.0248
   },
   {
    "round": 39,
    "train": 3.8754,
    "test": 5.0141
   },
   {
    "round": 40,
    "train": 3.8607,
    "test": 5.0064
   },
   {
    "round": 41,
    "train": 3.8462,
    "test": 5.0016
   },
   {
    "round": 42,
    "train": 3.8334,
    "test": 4.9939
   },
   {
    "round": 43,
    "train": 3.8215,
    "test": 4.9894
   },
   {
    "round": 44,
    "train": 3.8066,
    "test": 4.9856
   },
   {
    "round": 45,
    "train": 3.7934,
    "test": 4.9806
   },
   {
    "round": 46,
    "train": 3.7825,
    "test": 4.9743
   },
   {
    "round": 47,
    "train": 3.7724,
    "test": 4.9719
   },
   {
    "round": 48,
    "train": 3.7609,
    "test": 4.971
   },
   {
    "round": 49,
    "train": 3.7511,
    "test": 4.9682
   },
   {
    "round": 50,
    "train": 3.7411,
    "test": 4.9662
   },
   {
    "round": 51,
    "train": 3.73,
    "test": 4.9648
   },
   {
    "round": 52,
    "train": 3.723,
    "test": 4.9623
   },
   {
    "round": 53,
    "train": 3.715,
    "test": 4.9614
   },
   {
    "round": 54,
    "train": 3.7058,
    "test": 4.9591
   },
   {
    "round": 55,
    "train": 3.6996,
    "test": 4.9579
   },
   {
    "round": 56,
    "train": 3.6912,
    "test": 4.9568
   },
   {
    "round": 57,
    "train": 3.6851,
    "test": 4.9565
   },
   {
    "round": 58,
    "train": 3.6775,
    "test": 4.9558
   },
   {
    "round": 59,
    "train": 3.6704,
    "test": 4.9565
   },
   {
    "round": 60,
    "train": 3.6641,
    "test": 4.957
   }
  ]
 },
 "hist": {
  "train": 3.7336419485328847,
  "test": 4.975812636651436,
  "gainEvals": 1262724,
  "rowTouches": 3356816,
  "histBuilds": 7440,
  "histSubtracts": 7200,
  "nBins": [
   255,
   255,
   254,
   16
  ],
  "curve": [
   {
    "round": 0,
    "train": 13.9026,
    "test": 14.5194
   },
   {
    "round": 1,
    "train": 12.7646,
    "test": 13.3989
   },
   {
    "round": 2,
    "train": 11.7548,
    "test": 12.3927
   },
   {
    "round": 3,
    "train": 10.8506,
    "test": 11.5083
   },
   {
    "round": 4,
    "train": 10.0547,
    "test": 10.7282
   },
   {
    "round": 5,
    "train": 9.342,
    "test": 10.03
   },
   {
    "round": 6,
    "train": 8.7155,
    "test": 9.4157
   },
   {
    "round": 7,
    "train": 8.1673,
    "test": 8.8836
   },
   {
    "round": 8,
    "train": 7.679,
    "test": 8.4147
   },
   {
    "round": 9,
    "train": 7.248,
    "test": 7.9961
   },
   {
    "round": 10,
    "train": 6.8562,
    "test": 7.629
   },
   {
    "round": 11,
    "train": 6.5202,
    "test": 7.3142
   },
   {
    "round": 12,
    "train": 6.2186,
    "test": 7.0376
   },
   {
    "round": 13,
    "train": 5.9525,
    "test": 6.7896
   },
   {
    "round": 14,
    "train": 5.7253,
    "test": 6.5851
   },
   {
    "round": 15,
    "train": 5.5147,
    "test": 6.3882
   },
   {
    "round": 16,
    "train": 5.3239,
    "test": 6.2159
   },
   {
    "round": 17,
    "train": 5.165,
    "test": 6.0727
   },
   {
    "round": 18,
    "train": 5.0198,
    "test": 5.943
   },
   {
    "round": 19,
    "train": 4.891,
    "test": 5.8287
   },
   {
    "round": 20,
    "train": 4.7806,
    "test": 5.7318
   },
   {
    "round": 21,
    "train": 4.6787,
    "test": 5.6407
   },
   {
    "round": 22,
    "train": 4.5912,
    "test": 5.5668
   },
   {
    "round": 23,
    "train": 4.507,
    "test": 5.4929
   },
   {
    "round": 24,
    "train": 4.4373,
    "test": 5.431
   },
   {
    "round": 25,
    "train": 4.3718,
    "test": 5.3793
   },
   {
    "round": 26,
    "train": 4.3161,
    "test": 5.3352
   },
   {
    "round": 27,
    "train": 4.2654,
    "test": 5.2905
   },
   {
    "round": 28,
    "train": 4.2187,
    "test": 5.2538
   },
   {
    "round": 29,
    "train": 4.1801,
    "test": 5.2234
   },
   {
    "round": 30,
    "train": 4.1419,
    "test": 5.1991
   },
   {
    "round": 31,
    "train": 4.1059,
    "test": 5.1701
   },
   {
    "round": 32,
    "train": 4.0788,
    "test": 5.1486
   },
   {
    "round": 33,
    "train": 4.0494,
    "test": 5.1246
   },
   {
    "round": 34,
    "train": 4.0258,
    "test": 5.1097
   },
   {
    "round": 35,
    "train": 4.0014,
    "test": 5.0958
   },
   {
    "round": 36,
    "train": 3.9806,
    "test": 5.0801
   },
   {
    "round": 37,
    "train": 3.9625,
    "test": 5.0666
   },
   {
    "round": 38,
    "train": 3.9461,
    "test": 5.0552
   },
   {
    "round": 39,
    "train": 3.9293,
    "test": 5.0484
   },
   {
    "round": 40,
    "train": 3.9153,
    "test": 5.0377
   },
   {
    "round": 41,
    "train": 3.9005,
    "test": 5.0264
   },
   {
    "round": 42,
    "train": 3.8868,
    "test": 5.0179
   },
   {
    "round": 43,
    "train": 3.8758,
    "test": 5.011
   },
   {
    "round": 44,
    "train": 3.8648,
    "test": 5.0031
   },
   {
    "round": 45,
    "train": 3.853,
    "test": 4.9973
   },
   {
    "round": 46,
    "train": 3.8433,
    "test": 4.9963
   },
   {
    "round": 47,
    "train": 3.8323,
    "test": 4.9949
   },
   {
    "round": 48,
    "train": 3.823,
    "test": 4.9905
   },
   {
    "round": 49,
    "train": 3.8145,
    "test": 4.9848
   },
   {
    "round": 50,
    "train": 3.8063,
    "test": 4.9837
   },
   {
    "round": 51,
    "train": 3.7983,
    "test": 4.9793
   },
   {
    "round": 52,
    "train": 3.7892,
    "test": 4.9781
   },
   {
    "round": 53,
    "train": 3.7826,
    "test": 4.9777
   },
   {
    "round": 54,
    "train": 3.7743,
    "test": 4.9781
   },
   {
    "round": 55,
    "train": 3.7668,
    "test": 4.9776
   },
   {
    "round": 56,
    "train": 3.7586,
    "test": 4.9788
   },
   {
    "round": 57,
    "train": 3.7528,
    "test": 4.9756
   },
   {
    "round": 58,
    "train": 3.7453,
    "test": 4.9751
   },
   {
    "round": 59,
    "train": 3.7395,
    "test": 4.9749
   },
   {
    "round": 60,
    "train": 3.7336,
    "test": 4.9758
   }
  ]
 },
 "histNoSubtract": {
  "train": 3.7336419485328847,
  "test": 4.975812636651436,
  "gainEvals": 1262724,
  "rowTouches": 10346572,
  "histBuilds": 14640,
  "histSubtracts": 0,
  "nBins": [
   255,
   255,
   254,
   16
  ],
  "curve": [
   {
    "round": 0,
    "train": 13.9026,
    "test": 14.5194
   },
   {
    "round": 1,
    "train": 12.7646,
    "test": 13.3989
   },
   {
    "round": 2,
    "train": 11.7548,
    "test": 12.3927
   },
   {
    "round": 3,
    "train": 10.8506,
    "test": 11.5083
   },
   {
    "round": 4,
    "train": 10.0547,
    "test": 10.7282
   },
   {
    "round": 5,
    "train": 9.342,
    "test": 10.03
   },
   {
    "round": 6,
    "train": 8.7155,
    "test": 9.4157
   },
   {
    "round": 7,
    "train": 8.1673,
    "test": 8.8836
   },
   {
    "round": 8,
    "train": 7.679,
    "test": 8.4147
   },
   {
    "round": 9,
    "train": 7.248,
    "test": 7.9961
   },
   {
    "round": 10,
    "train": 6.8562,
    "test": 7.629
   },
   {
    "round": 11,
    "train": 6.5202,
    "test": 7.3142
   },
   {
    "round": 12,
    "train": 6.2186,
    "test": 7.0376
   },
   {
    "round": 13,
    "train": 5.9525,
    "test": 6.7896
   },
   {
    "round": 14,
    "train": 5.7253,
    "test": 6.5851
   },
   {
    "round": 15,
    "train": 5.5147,
    "test": 6.3882
   },
   {
    "round": 16,
    "train": 5.3239,
    "test": 6.2159
   },
   {
    "round": 17,
    "train": 5.165,
    "test": 6.0727
   },
   {
    "round": 18,
    "train": 5.0198,
    "test": 5.943
   },
   {
    "round": 19,
    "train": 4.891,
    "test": 5.8287
   },
   {
    "round": 20,
    "train": 4.7806,
    "test": 5.7318
   },
   {
    "round": 21,
    "train": 4.6787,
    "test": 5.6407
   },
   {
    "round": 22,
    "train": 4.5912,
    "test": 5.5668
   },
   {
    "round": 23,
    "train": 4.507,
    "test": 5.4929
   },
   {
    "round": 24,
    "train": 4.4373,
    "test": 5.431
   },
   {
    "round": 25,
    "train": 4.3718,
    "test": 5.3793
   },
   {
    "round": 26,
    "train": 4.3161,
    "test": 5.3352
   },
   {
    "round": 27,
    "train": 4.2654,
    "test": 5.2905
   },
   {
    "round": 28,
    "train": 4.2187,
    "test": 5.2538
   },
   {
    "round": 29,
    "train": 4.1801,
    "test": 5.2234
   },
   {
    "round": 30,
    "train": 4.1419,
    "test": 5.1991
   },
   {
    "round": 31,
    "train": 4.1059,
    "test": 5.1701
   },
   {
    "round": 32,
    "train": 4.0788,
    "test": 5.1486
   },
   {
    "round": 33,
    "train": 4.0494,
    "test": 5.1246
   },
   {
    "round": 34,
    "train": 4.0258,
    "test": 5.1097
   },
   {
    "round": 35,
    "train": 4.0014,
    "test": 5.0958
   },
   {
    "round": 36,
    "train": 3.9806,
    "test": 5.0801
   },
   {
    "round": 37,
    "train": 3.9625,
    "test": 5.0666
   },
   {
    "round": 38,
    "train": 3.9461,
    "test": 5.0552
   },
   {
    "round": 39,
    "train": 3.9293,
    "test": 5.0484
   },
   {
    "round": 40,
    "train": 3.9153,
    "test": 5.0377
   },
   {
    "round": 41,
    "train": 3.9005,
    "test": 5.0264
   },
   {
    "round": 42,
    "train": 3.8868,
    "test": 5.0179
   },
   {
    "round": 43,
    "train": 3.8758,
    "test": 5.011
   },
   {
    "round": 44,
    "train": 3.8648,
    "test": 5.0031
   },
   {
    "round": 45,
    "train": 3.853,
    "test": 4.9973
   },
   {
    "round": 46,
    "train": 3.8433,
    "test": 4.9963
   },
   {
    "round": 47,
    "train": 3.8323,
    "test": 4.9949
   },
   {
    "round": 48,
    "train": 3.823,
    "test": 4.9905
   },
   {
    "round": 49,
    "train": 3.8145,
    "test": 4.9848
   },
   {
    "round": 50,
    "train": 3.8063,
    "test": 4.9837
   },
   {
    "round": 51,
    "train": 3.7983,
    "test": 4.9793
   },
   {
    "round": 52,
    "train": 3.7892,
    "test": 4.9781
   },
   {
    "round": 53,
    "train": 3.7826,
    "test": 4.9777
   },
   {
    "round": 54,
    "train": 3.7743,
    "test": 4.9781
   },
   {
    "round": 55,
    "train": 3.7668,
    "test": 4.9776
   },
   {
    "round": 56,
    "train": 3.7586,
    "test": 4.9788
   },
   {
    "round": 57,
    "train": 3.7528,
    "test": 4.9756
   },
   {
    "round": 58,
    "train": 3.7453,
    "test": 4.9751
   },
   {
    "round": 59,
    "train": 3.7395,
    "test": 4.9749
   },
   {
    "round": 60,
    "train": 3.7336,
    "test": 4.9758
   }
  ]
 },
 "splitTrace": [
  {
   "depth": 0,
   "nodeSize": 6000,
   "left": 5036,
   "right": 964,
   "smaller": 964,
   "feature": 0,
   "gain": 264681.9439666335
  },
  {
   "depth": 1,
   "nodeSize": 964,
   "left": 729,
   "right": 235,
   "smaller": 235,
   "feature": 0,
   "gain": 65169.03084433256
  },
  {
   "depth": 1,
   "nodeSize": 5036,
   "left": 2871,
   "right": 2165,
   "smaller": 2165,
   "feature": 0,
   "gain": 50626.2088378724
  },
  {
   "depth": 2,
   "nodeSize": 2871,
   "left": 2133,
   "right": 738,
   "smaller": 738,
   "feature": 3,
   "gain": 18413.948305265076
  },
  {
   "depth": 2,
   "nodeSize": 235,
   "left": 212,
   "right": 23,
   "smaller": 23,
   "feature": 0,
   "gain": 18293.03340917421
  },
  {
   "depth": 2,
   "nodeSize": 2165,
   "left": 1629,
   "right": 536,
   "smaller": 536,
   "feature": 3,
   "gain": 12405.38913499508
  },
  {
   "depth": 2,
   "nodeSize": 729,
   "left": 447,
   "right": 282,
   "smaller": 282,
   "feature": 0,
   "gain": 6168.65241816442
  },
  {
   "depth": 3,
   "nodeSize": 1629,
   "left": 904,
   "right": 725,
   "smaller": 725,
   "feature": 0,
   "gain": 6120.092308490648
  },
  {
   "depth": 3,
   "nodeSize": 2133,
   "left": 842,
   "right": 1291,
   "smaller": 842,
   "feature": 0,
   "gain": 4896.05797059297
  },
  {
   "depth": 3,
   "nodeSize": 212,
   "left": 165,
   "right": 47,
   "smaller": 47,
   "feature": 0,
   "gain": 3711.301336921111
  },
  {
   "depth": 3,
   "nodeSize": 738,
   "left": 438,
   "right": 300,
   "smaller": 300,
   "feature": 3,
   "gain": 3079.9934799275825
  },
  {
   "depth": 3,
   "nodeSize": 447,
   "left": 264,
   "right": 183,
   "smaller": 183,
   "feature": 3,
   "gain": 2721.664190824711
  },
  {
   "depth": 3,
   "nodeSize": 536,
   "left": 318,
   "right": 218,
   "smaller": 218,
   "feature": 0,
   "gain": 2664.040021085537
  },
  {
   "depth": 4,
   "nodeSize": 1291,
   "left": 802,
   "right": 489,
   "smaller": 489,
   "feature": 3,
   "gain": 1803.803254409635
  },
  {
   "depth": 3,
   "nodeSize": 282,
   "left": 169,
   "right": 113,
   "smaller": 113,
   "feature": 3,
   "gain": 1728.9814929707645
  },
  {
   "depth": 4,
   "nodeSize": 904,
   "left": 569,
   "right": 335,
   "smaller": 335,
   "feature": 3,
   "gain": 1512.8930107127717
  },
  {
   "depth": 4,
   "nodeSize": 842,
   "left": 520,
   "right": 322,
   "smaller": 322,
   "feature": 2,
   "gain": 1371.9170028304652
  },
  {
   "depth": 4,
   "nodeSize": 725,
   "left": 465,
   "right": 260,
   "smaller": 260,
   "feature": 0,
   "gain": 1326.686900830135
  },
  {
   "depth": 5,
   "nodeSize": 520,
   "left": 306,
   "right": 214,
   "smaller": 214,
   "feature": 2,
   "gain": 1225.6423231833687
  },
  {
   "depth": 4,
   "nodeSize": 318,
   "left": 186,
   "right": 132,
   "smaller": 132,
   "feature": 3,
   "gain": 1216.1866433938571
  },
  {
   "depth": 5,
   "nodeSize": 322,
   "left": 264,
   "right": 58,
   "smaller": 58,
   "feature": 2,
   "gain": 1143.4394550235193
  },
  {
   "depth": 5,
   "nodeSize": 802,
   "left": 549,
   "right": 253,
   "smaller": 253,
   "feature": 2,
   "gain": 1090.1407218836175
  },
  {
   "depth": 6,
   "nodeSize": 306,
   "left": 86,
   "right": 220,
   "smaller": 86,
   "feature": 2,
   "gain": 1089.5098800718552
  },
  {
   "depth": 6,
   "nodeSize": 253,
   "left": 165,
   "right": 88,
   "smaller": 88,
   "feature": 2,
   "gain": 1053.327523826938
  },
  {
   "depth": 5,
   "nodeSize": 569,
   "left": 348,
   "right": 221,
   "smaller": 221,
   "feature": 2,
   "gain": 1010.8133475130535
  },
  {
   "depth": 6,
   "nodeSize": 348,
   "left": 188,
   "right": 160,
   "smaller": 160,
   "feature": 2,
   "gain": 1046.951984609721
  },
  {
   "depth": 5,
   "nodeSize": 465,
   "left": 184,
   "right": 281,
   "smaller": 184,
   "feature": 3,
   "gain": 936.689557665955
  },
  {
   "depth": 6,
   "nodeSize": 549,
   "left": 341,
   "right": 208,
   "smaller": 208,
   "feature": 0,
   "gain": 794.094981352584
  },
  {
   "depth": 4,
   "nodeSize": 438,
   "left": 286,
   "right": 152,
   "smaller": 152,
   "feature": 0,
   "gain": 771.4700683736669
  },
  {
   "depth": 4,
   "nodeSize": 218,
   "left": 192,
   "right": 26,
   "smaller": 26,
   "feature": 3,
   "gain": 714.6161994526228
  }
 ],
 "binSweep": [
  {
   "maxBin": 2,
   "train": 10.89328418464721,
   "test": 11.538165122849817,
   "gainEvals": 1560,
   "rowTouches": 4100492,
   "histBuilds": 3788,
   "histSubtracts": 3548,
   "nBins": [
    2,
    2,
    2,
    2
   ],
   "curve": [
    {
     "round": 0,
     "train": 13.9026,
     "test": 14.5194
    },
    {
     "round": 1,
     "train": 13.3842,
     "test": 14.0122
    },
    {
     "round": 2,
     "train": 12.9489,
     "test": 13.5864
    },
    {
     "round": 3,
     "train": 12.5851,
     "test": 13.2302
    },
    {
     "round": 4,
     "train": 12.2824,
     "test": 12.9335
    },
    {
     "round": 5,
     "train": 12.0315,
     "test": 12.687
    },
    {
     "round": 6,
     "train": 11.8242,
     "test": 12.4831
    },
    {
     "round": 7,
     "train": 11.6535,
     "test": 12.3147
    },
    {
     "round": 8,
     "train": 11.5133,
     "test": 12.176
    },
    {
     "round": 9,
     "train": 11.3984,
     "test": 12.062
    },
    {
     "round": 10,
     "train": 11.3044,
     "test": 11.9683
    },
    {
     "round": 11,
     "train": 11.2277,
     "test": 11.8915
    },
    {
     "round": 12,
     "train": 11.1651,
     "test": 11.8285
    },
    {
     "round": 13,
     "train": 11.1141,
     "test": 11.7768
    },
    {
     "round": 14,
     "train": 11.0726,
     "test": 11.7345
    },
    {
     "round": 15,
     "train": 11.0388,
     "test": 11.6999
    },
    {
     "round": 16,
     "train": 11.0114,
     "test": 11.6715
    },
    {
     "round": 17,
     "train": 10.9891,
     "test": 11.6482
    },
    {
     "round": 18,
     "train": 10.971,
     "test": 11.6291
    },
    {
     "round": 19,
     "train": 10.9563,
     "test": 11.6134
    },
    {
     "round": 20,
     "train": 10.9444,
     "test": 11.6006
    },
    {
     "round": 21,
     "train": 10.9347,
     "test": 11.59
    },
    {
     "round": 22,
     "train": 10.9269,
     "test": 11.5813
    },
    {
     "round": 23,
     "train": 10.9205,
     "test": 11.5741
    },
    {
     "round": 24,
     "train": 10.9154,
     "test": 11.5682
    },
    {
     "round": 25,
     "train": 10.9112,
     "test": 11.5633
    },
    {
     "round": 26,
     "train": 10.9078,
     "test": 11.5592
    },
    {
     "round": 27,
     "train": 10.905,
     "test": 11.5559
    },
    {
     "round": 28,
     "train": 10.9028,
     "test": 11.5531
    },
    {
     "round": 29,
     "train": 10.901,
     "test": 11.5508
    },
    {
     "round": 30,
     "train": 10.8995,
     "test": 11.5488
    },
    {
     "round": 31,
     "train": 10.8984,
     "test": 11.5472
    },
    {
     "round": 32,
     "train": 10.8974,
     "test": 11.5458
    },
    {
     "round": 33,
     "train": 10.8966,
     "test": 11.5447
    },
    {
     "round": 34,
     "train": 10.896,
     "test": 11.5437
    },
    {
     "round": 35,
     "train": 10.8955,
     "test": 11.5429
    },
    {
     "round": 36,
     "train": 10.895,
     "test": 11.5423
    },
    {
     "round": 37,
     "train": 10.8947,
     "test": 11.5417
    },
    {
     "round": 38,
     "train": 10.8944,
     "test": 11.5412
    },
    {
     "round": 39,
     "train": 10.8942,
     "test": 11.5408
    },
    {
     "round": 40,
     "train": 10.894,
     "test": 11.5404
    },
    {
     "round": 41,
     "train": 10.8939,
     "test": 11.5401
    },
    {
     "round": 42,
     "train": 10.8938,
     "test": 11.5398
    },
    {
     "round": 43,
     "train": 10.8937,
     "test": 11.5396
    },
    {
     "round": 44,
     "train": 10.8936,
     "test": 11.5394
    },
    {
     "round": 45,
     "train": 10.8935,
     "test": 11.5392
    },
    {
     "round": 46,
     "train": 10.8935,
     "test": 11.5391
    },
    {
     "round": 47,
     "train": 10.8934,
     "test": 11.5389
    },
    {
     "round": 48,
     "train": 10.8934,
     "test": 11.5388
    },
    {
     "round": 49,
     "train": 10.8934,
     "test": 11.5387
    },
    {
     "round": 50,
     "train": 10.8934,
     "test": 11.5386
    },
    {
     "round": 51,
     "train": 10.8933,
     "test": 11.5386
    },
    {
     "round": 52,
     "train": 10.8933,
     "test": 11.5385
    },
    {
     "round": 53,
     "train": 10.8933,
     "test": 11.5384
    },
    {
     "round": 54,
     "train": 10.8933,
     "test": 11.5384
    },
    {
     "round": 55,
     "train": 10.8933,
     "test": 11.5383
    },
    {
     "round": 56,
     "train": 10.8933,
     "test": 11.5383
    },
    {
     "round": 57,
     "train": 10.8933,
     "test": 11.5383
    },
    {
     "round": 58,
     "train": 10.8933,
     "test": 11.5382
    },
    {
     "round": 59,
     "train": 10.8933,
     "test": 11.5382
    },
    {
     "round": 60,
     "train": 10.8933,
     "test": 11.5382
    }
   ]
  },
  {
   "maxBin": 4,
   "train": 8.784940588077331,
   "test": 9.744888724504365,
   "gainEvals": 15068,
   "rowTouches": 3642412,
   "histBuilds": 7440,
   "histSubtracts": 7200,
   "nBins": [
    4,
    4,
    4,
    4
   ],
   "curve": [
    {
     "round": 0,
     "train": 13.9026,
     "test": 14.5194
    },
    {
     "round": 1,
     "train": 13.1089,
     "test": 13.7525
    },
    {
     "round": 2,
     "train": 12.4277,
     "test": 13.0969
    },
    {
     "round": 3,
     "train": 11.8443,
     "test": 12.5412
    },
    {
     "round": 4,
     "train": 11.348,
     "test": 12.0716
    },
    {
     "round": 5,
     "train": 10.9296,
     "test": 11.6752
    },
    {
     "round": 6,
     "train": 10.5758,
     "test": 11.345
    },
    {
     "round": 7,
     "train": 10.2796,
     "test": 11.0678
    },
    {
     "round": 8,
     "train": 10.0322,
     "test": 10.8389
    },
    {
     "round": 9,
     "train": 9.8264,
     "test": 10.6472
    },
    {
     "round": 10,
     "train": 9.656,
     "test": 10.4883
    },
    {
     "round": 11,
     "train": 9.5142,
     "test": 10.3588
    },
    {
     "round": 12,
     "train": 9.3972,
     "test": 10.2478
    },
    {
     "round": 13,
     "train": 9.2999,
     "test": 10.1563
    },
    {
     "round": 14,
     "train": 9.2199,
     "test": 10.0814
    },
    {
     "round": 15,
     "train": 9.1535,
     "test": 10.0196
    },
    {
     "round": 16,
     "train": 9.0987,
     "test": 9.969
    },
    {
     "round": 17,
     "train": 9.0529,
     "test": 9.9261
    },
    {
     "round": 18,
     "train": 9.0143,
     "test": 9.8909
    },
    {
     "round": 19,
     "train": 8.9824,
     "test": 9.8599
    },
    {
     "round": 20,
     "train": 8.955,
     "test": 9.835
    },
    {
     "round": 21,
     "train": 8.9331,
     "test": 9.8163
    },
    {
     "round": 22,
     "train": 8.9145,
     "test": 9.7996
    },
    {
     "round": 23,
     "train": 8.8986,
     "test": 9.7847
    },
    {
     "round": 24,
     "train": 8.8855,
     "test": 9.7738
    },
    {
     "round": 25,
     "train": 8.8741,
     "test": 9.7641
    },
    {
     "round": 26,
     "train": 8.8641,
     "test": 9.756
    },
    {
     "round": 27,
     "train": 8.8559,
     "test": 9.7484
    },
    {
     "round": 28,
     "train": 8.8487,
     "test": 9.7426
    },
    {
     "round": 29,
     "train": 8.8424,
     "test": 9.7385
    },
    {
     "round": 30,
     "train": 8.8373,
     "test": 9.7357
    },
    {
     "round": 31,
     "train": 8.833,
     "test": 9.7313
    },
    {
     "round": 32,
     "train": 8.828,
     "test": 9.7309
    },
    {
     "round": 33,
     "train": 8.8246,
     "test": 9.7284
    },
    {
     "round": 34,
     "train": 8.8216,
     "test": 9.7264
    },
    {
     "round": 35,
     "train": 8.8186,
     "test": 9.7256
    },
    {
     "round": 36,
     "train": 8.8162,
     "test": 9.7253
    },
    {
     "round": 37,
     "train": 8.814,
     "test": 9.7242
    },
    {
     "round": 38,
     "train": 8.8112,
     "test": 9.7261
    },
    {
     "round": 39,
     "train": 8.8095,
     "test": 9.7253
    },
    {
     "round": 40,
     "train": 8.8079,
     "test": 9.7252
    },
    {
     "round": 41,
     "train": 8.8058,
     "test": 9.7261
    },
    {
     "round": 42,
     "train": 8.8036,
     "test": 9.7278
    },
    {
     "round": 43,
     "train": 8.8017,
     "test": 9.7292
    },
    {
     "round": 44,
     "train": 8.8001,
     "test": 9.7303
    },
    {
     "round": 45,
     "train": 8.799,
     "test": 9.7298
    },
    {
     "round": 46,
     "train": 8.7977,
     "test": 9.7312
    },
    {
     "round": 47,
     "train": 8.7964,
     "test": 9.731
    },
    {
     "round": 48,
     "train": 8.7954,
     "test": 9.7322
    },
    {
     "round": 49,
     "train": 8.7944,
     "test": 9.7335
    },
    {
     "round": 50,
     "train": 8.7934,
     "test": 9.7342
    },
    {
     "round": 51,
     "train": 8.7922,
     "test": 9.7343
    },
    {
     "round": 52,
     "train": 8.7912,
     "test": 9.7353
    },
    {
     "round": 53,
     "train": 8.7904,
     "test": 9.7364
    },
    {
     "round": 54,
     "train": 8.7897,
     "test": 9.7372
    },
    {
     "round": 55,
     "train": 8.7888,
     "test": 9.7383
    },
    {
     "round": 56,
     "train": 8.7881,
     "test": 9.7404
    },
    {
     "round": 57,
     "train": 8.7871,
     "test": 9.7418
    },
    {
     "round": 58,
     "train": 8.7862,
     "test": 9.743
    },
    {
     "round": 59,
     "train": 8.7854,
     "test": 9.7436
    },
    {
     "round": 60,
     "train": 8.7849,
     "test": 9.7449
    }
   ]
  },
  {
   "maxBin": 8,
   "train": 6.583043728057616,
   "test": 7.942572553818205,
   "gainEvals": 42578,
   "rowTouches": 3465692,
   "histBuilds": 7440,
   "histSubtracts": 7200,
   "nBins": [
    8,
    8,
    8,
    8
   ],
   "curve": [
    {
     "round": 0,
     "train": 13.9026,
     "test": 14.5194
    },
    {
     "round": 1,
     "train": 12.951,
     "test": 13.6014
    },
    {
     "round": 2,
     "train": 12.1174,
     "test": 12.8001
    },
    {
     "round": 3,
     "train": 11.3862,
     "test": 12.0988
    },
    {
     "round": 4,
     "train": 10.743,
     "test": 11.4948
    },
    {
     "round": 5,
     "train": 10.1945,
     "test": 10.9846
    },
    {
     "round": 6,
     "train": 9.7165,
     "test": 10.5331
    },
    {
     "round": 7,
     "train": 9.3063,
     "test": 10.1527
    },
    {
     "round": 8,
     "train": 8.9469,
     "test": 9.8227
    },
    {
     "round": 9,
     "train": 8.6443,
     "test": 9.5498
    },
    {
     "round": 10,
     "train": 8.38,
     "test": 9.3061
    },
    {
     "round": 11,
     "train": 8.1612,
     "test": 9.1107
    },
    {
     "round": 12,
     "train": 7.9695,
     "test": 8.9411
    },
    {
     "round": 13,
     "train": 7.8065,
     "test": 8.7955
    },
    {
     "round": 14,
     "train": 7.6581,
     "test": 8.6728
    },
    {
     "round": 15,
     "train": 7.5391,
     "test": 8.5674
    },
    {
     "round": 16,
     "train": 7.4348,
     "test": 8.4847
    },
    {
     "round": 17,
     "train": 7.3442,
     "test": 8.4124
    },
    {
     "round": 18,
     "train": 7.2669,
     "test": 8.3536
    },
    {
     "round": 19,
     "train": 7.1985,
     "test": 8.2996
    },
    {
     "round": 20,
     "train": 7.1418,
     "test": 8.256
    },
    {
     "round": 21,
     "train": 7.0922,
     "test": 8.2209
    },
    {
     "round": 22,
     "train": 7.0475,
     "test": 8.1829
    },
    {
     "round": 23,
     "train": 7.0062,
     "test": 8.1522
    },
    {
     "round": 24,
     "train": 6.9716,
     "test": 8.1304
    },
    {
     "round": 25,
     "train": 6.94,
     "test": 8.1085
    },
    {
     "round": 26,
     "train": 6.9107,
     "test": 8.0819
    },
    {
     "round": 27,
     "train": 6.8845,
     "test": 8.0608
    },
    {
     "round": 28,
     "train": 6.8625,
     "test": 8.0459
    },
    {
     "round": 29,
     "train": 6.8397,
     "test": 8.0329
    },
    {
     "round": 30,
     "train": 6.8184,
     "test": 8.0221
    },
    {
     "round": 31,
     "train": 6.802,
     "test": 8.0094
    },
    {
     "round": 32,
     "train": 6.7884,
     "test": 8.0024
    },
    {
     "round": 33,
     "train": 6.7744,
     "test": 7.9917
    },
    {
     "round": 34,
     "train": 6.7581,
     "test": 7.9826
    },
    {
     "round": 35,
     "train": 6.7464,
     "test": 7.9753
    },
    {
     "round": 36,
     "train": 6.7364,
     "test": 7.9683
    },
    {
     "round": 37,
     "train": 6.7218,
     "test": 7.9608
    },
    {
     "round": 38,
     "train": 6.7109,
     "test": 7.9602
    },
    {
     "round": 39,
     "train": 6.7001,
     "test": 7.9554
    },
    {
     "round": 40,
     "train": 6.6922,
     "test": 7.952
    },
    {
     "round": 41,
     "train": 6.6831,
     "test": 7.9483
    },
    {
     "round": 42,
     "train": 6.6747,
     "test": 7.9475
    },
    {
     "round": 43,
     "train": 6.6675,
     "test": 7.9429
    },
    {
     "round": 44,
     "train": 6.6599,
     "test": 7.9379
    },
    {
     "round": 45,
     "train": 6.6519,
     "test": 7.9341
    },
    {
     "round": 46,
     "train": 6.6455,
     "test": 7.9308
    },
    {
     "round": 47,
     "train": 6.6408,
     "test": 7.9316
    },
    {
     "round": 48,
     "train": 6.6351,
     "test": 7.9348
    },
    {
     "round": 49,
     "train": 6.6305,
     "test": 7.9385
    },
    {
     "round": 50,
     "train": 6.6238,
     "test": 7.9356
    },
    {
     "round": 51,
     "train": 6.6188,
     "test": 7.9343
    },
    {
     "round": 52,
     "train": 6.6152,
     "test": 7.9385
    },
    {
     "round": 53,
     "train": 6.612,
     "test": 7.9379
    },
    {
     "round": 54,
     "train": 6.6075,
     "test": 7.9374
    },
    {
     "round": 55,
     "train": 6.6026,
     "test": 7.936
    },
    {
     "round": 56,
     "train": 6.5966,
     "test": 7.9392
    },
    {
     "round": 57,
     "train": 6.5937,
     "test": 7.9417
    },
    {
     "round": 58,
     "train": 6.5894,
     "test": 7.9421
    },
    {
     "round": 59,
     "train": 6.5856,
     "test": 7.9419
    },
    {
     "round": 60,
     "train": 6.583,
     "test": 7.9426
    }
   ]
  },
  {
   "maxBin": 16,
   "train": 5.268875442147986,
   "test": 6.871619596760051,
   "gainEvals": 87298,
   "rowTouches": 3417736,
   "histBuilds": 7440,
   "histSubtracts": 7200,
   "nBins": [
    16,
    16,
    16,
    16
   ],
   "curve": [
    {
     "round": 0,
     "train": 13.9026,
     "test": 14.5194
    },
    {
     "round": 1,
     "train": 12.8592,
     "test": 13.5093
    },
    {
     "round": 2,
     "train": 11.9414,
     "test": 12.6266
    },
    {
     "round": 3,
     "train": 11.1294,
     "test": 11.845
    },
    {
     "round": 4,
     "train": 10.4243,
     "test": 11.1764
    },
    {
     "round": 5,
     "train": 9.804,
     "test": 10.5926
    },
    {
     "round": 6,
     "train": 9.2599,
     "test": 10.0851
    },
    {
     "round": 7,
     "train": 8.7913,
     "test": 9.6516
    },
    {
     "round": 8,
     "train": 8.3779,
     "test": 9.2705
    },
    {
     "round": 9,
     "train": 8.0123,
     "test": 8.9555
    },
    {
     "round": 10,
     "train": 7.6996,
     "test": 8.6684
    },
    {
     "round": 11,
     "train": 7.4238,
     "test": 8.421
    },
    {
     "round": 12,
     "train": 7.1891,
     "test": 8.2185
    },
    {
     "round": 13,
     "train": 6.9803,
     "test": 8.0328
    },
    {
     "round": 14,
     "train": 6.7985,
     "test": 7.8908
    },
    {
     "round": 15,
     "train": 6.6456,
     "test": 7.7586
    },
    {
     "round": 16,
     "train": 6.5001,
     "test": 7.6476
    },
    {
     "round": 17,
     "train": 6.3831,
     "test": 7.559
    },
    {
     "round": 18,
     "train": 6.2788,
     "test": 7.4827
    },
    {
     "round": 19,
     "train": 6.1815,
     "test": 7.3955
    },
    {
     "round": 20,
     "train": 6.103,
     "test": 7.3393
    },
    {
     "round": 21,
     "train": 6.0282,
     "test": 7.2736
    },
    {
     "round": 22,
     "train": 5.96,
     "test": 7.2275
    },
    {
     "round": 23,
     "train": 5.8955,
     "test": 7.1753
    },
    {
     "round": 24,
     "train": 5.8448,
     "test": 7.1359
    },
    {
     "round": 25,
     "train": 5.792,
     "test": 7.0932
    },
    {
     "round": 26,
     "train": 5.751,
     "test": 7.0637
    },
    {
     "round": 27,
     "train": 5.717,
     "test": 7.0409
    },
    {
     "round": 28,
     "train": 5.6831,
     "test": 7.0216
    },
    {
     "round": 29,
     "train": 5.65,
     "test": 6.9987
    },
    {
     "round": 30,
     "train": 5.6217,
     "test": 6.982
    },
    {
     "round": 31,
     "train": 5.5954,
     "test": 6.9698
    },
    {
     "round": 32,
     "train": 5.5696,
     "test": 6.9544
    },
    {
     "round": 33,
     "train": 5.5472,
     "test": 6.9461
    },
    {
     "round": 34,
     "train": 5.5297,
     "test": 6.9376
    },
    {
     "round": 35,
     "train": 5.5105,
     "test": 6.9267
    },
    {
     "round": 36,
     "train": 5.4946,
     "test": 6.9235
    },
    {
     "round": 37,
     "train": 5.4779,
     "test": 6.9185
    },
    {
     "round": 38,
     "train": 5.4654,
     "test": 6.9184
    },
    {
     "round": 39,
     "train": 5.4516,
     "test": 6.9107
    },
    {
     "round": 40,
     "train": 5.4376,
     "test": 6.9046
    },
    {
     "round": 41,
     "train": 5.4277,
     "test": 6.8992
    },
    {
     "round": 42,
     "train": 5.4161,
     "test": 6.8948
    },
    {
     "round": 43,
     "train": 5.4028,
     "test": 6.8915
    },
    {
     "round": 44,
     "train": 5.3901,
     "test": 6.8912
    },
    {
     "round": 45,
     "train": 5.3781,
     "test": 6.8862
    },
    {
     "round": 46,
     "train": 5.3682,
     "test": 6.8904
    },
    {
     "round": 47,
     "train": 5.3572,
     "test": 6.8891
    },
    {
     "round": 48,
     "train": 5.3474,
     "test": 6.8869
    },
    {
     "round": 49,
     "train": 5.3389,
     "test": 6.889
    },
    {
     "round": 50,
     "train": 5.3317,
     "test": 6.8845
    },
    {
     "round": 51,
     "train": 5.3239,
     "test": 6.8826
    },
    {
     "round": 52,
     "train": 5.3169,
     "test": 6.8816
    },
    {
     "round": 53,
     "train": 5.3114,
     "test": 6.8785
    },
    {
     "round": 54,
     "train": 5.3036,
     "test": 6.8745
    },
    {
     "round": 55,
     "train": 5.2967,
     "test": 6.8727
    },
    {
     "round": 56,
     "train": 5.2928,
     "test": 6.8724
    },
    {
     "round": 57,
     "train": 5.2886,
     "test": 6.8726
    },
    {
     "round": 58,
     "train": 5.2817,
     "test": 6.8702
    },
    {
     "round": 59,
     "train": 5.2737,
     "test": 6.8703
    },
    {
     "round": 60,
     "train": 5.2689,
     "test": 6.8716
    }
   ]
  },
  {
   "maxBin": 32,
   "train": 4.502246460971451,
   "test": 6.1718754205546595,
   "gainEvals": 164674,
   "rowTouches": 3393224,
   "histBuilds": 7440,
   "histSubtracts": 7200,
   "nBins": [
    32,
    32,
    32,
    16
   ],
   "curve": [
    {
     "round": 0,
     "train": 13.9026,
     "test": 14.5194
    },
    {
     "round": 1,
     "train": 12.81,
     "test": 13.4643
    },
    {
     "round": 2,
     "train": 11.8479,
     "test": 12.5418
    },
    {
     "round": 3,
     "train": 10.989,
     "test": 11.7262
    },
    {
     "round": 4,
     "train": 10.2354,
     "test": 11.0088
    },
    {
     "round": 5,
     "train": 9.5794,
     "test": 10.3923
    },
    {
     "round": 6,
     "train": 8.9936,
     "test": 9.8461
    },
    {
     "round": 7,
     "train": 8.483,
     "test": 9.3673
    },
    {
     "round": 8,
     "train": 8.0337,
     "test": 8.9542
    },
    {
     "round": 9,
     "train": 7.6434,
     "test": 8.5936
    },
    {
     "round": 10,
     "train": 7.3009,
     "test": 8.2818
    },
    {
     "round": 11,
     "train": 7.0036,
     "test": 8.0175
    },
    {
     "round": 12,
     "train": 6.7321,
     "test": 7.7867
    },
    {
     "round": 13,
     "train": 6.496,
     "test": 7.5748
    },
    {
     "round": 14,
     "train": 6.291,
     "test": 7.3946
    },
    {
     "round": 15,
     "train": 6.1129,
     "test": 7.2467
    },
    {
     "round": 16,
     "train": 5.9446,
     "test": 7.1052
    },
    {
     "round": 17,
     "train": 5.8103,
     "test": 7.0089
    },
    {
     "round": 18,
     "train": 5.6821,
     "test": 6.8929
    },
    {
     "round": 19,
     "train": 5.5668,
     "test": 6.7991
    },
    {
     "round": 20,
     "train": 5.4684,
     "test": 6.7199
    },
    {
     "round": 21,
     "train": 5.3831,
     "test": 6.6534
    },
    {
     "round": 22,
     "train": 5.3078,
     "test": 6.5858
    },
    {
     "round": 23,
     "train": 5.2361,
     "test": 6.5344
    },
    {
     "round": 24,
     "train": 5.1769,
     "test": 6.4869
    },
    {
     "round": 25,
     "train": 5.1207,
     "test": 6.4457
    },
    {
     "round": 26,
     "train": 5.0711,
     "test": 6.4157
    },
    {
     "round": 27,
     "train": 5.0229,
     "test": 6.3854
    },
    {
     "round": 28,
     "train": 4.9786,
     "test": 6.3478
    },
    {
     "round": 29,
     "train": 4.9447,
     "test": 6.3204
    },
    {
     "round": 30,
     "train": 4.9115,
     "test": 6.3061
    },
    {
     "round": 31,
     "train": 4.879,
     "test": 6.2966
    },
    {
     "round": 32,
     "train": 4.8499,
     "test": 6.2851
    },
    {
     "round": 33,
     "train": 4.8253,
     "test": 6.2749
    },
    {
     "round": 34,
     "train": 4.7994,
     "test": 6.264
    },
    {
     "round": 35,
     "train": 4.7769,
     "test": 6.2556
    },
    {
     "round": 36,
     "train": 4.7565,
     "test": 6.2468
    },
    {
     "round": 37,
     "train": 4.7396,
     "test": 6.2415
    },
    {
     "round": 38,
     "train": 4.7206,
     "test": 6.2348
    },
    {
     "round": 39,
     "train": 4.7048,
     "test": 6.2306
    },
    {
     "round": 40,
     "train": 4.6894,
     "test": 6.2244
    },
    {
     "round": 41,
     "train": 4.6762,
     "test": 6.2207
    },
    {
     "round": 42,
     "train": 4.6627,
     "test": 6.2171
    },
    {
     "round": 43,
     "train": 4.6517,
     "test": 6.2172
    },
    {
     "round": 44,
     "train": 4.6407,
     "test": 6.2182
    },
    {
     "round": 45,
     "train": 4.6266,
     "test": 6.2075
    },
    {
     "round": 46,
     "train": 4.6138,
     "test": 6.1988
    },
    {
     "round": 47,
     "train": 4.6053,
     "test": 6.1968
    },
    {
     "round": 48,
     "train": 4.5955,
     "test": 6.1896
    },
    {
     "round": 49,
     "train": 4.5855,
     "test": 6.1857
    },
    {
     "round": 50,
     "train": 4.5767,
     "test": 6.1868
    },
    {
     "round": 51,
     "train": 4.5677,
     "test": 6.1817
    },
    {
     "round": 52,
     "train": 4.559,
     "test": 6.183
    },
    {
     "round": 53,
     "train": 4.5507,
     "test": 6.1798
    },
    {
     "round": 54,
     "train": 4.5441,
     "test": 6.1808
    },
    {
     "round": 55,
     "train": 4.5356,
     "test": 6.1823
    },
    {
     "round": 56,
     "train": 4.5281,
     "test": 6.1801
    },
    {
     "round": 57,
     "train": 4.5225,
     "test": 6.1793
    },
    {
     "round": 58,
     "train": 4.5161,
     "test": 6.1742
    },
    {
     "round": 59,
     "train": 4.5109,
     "test": 6.1757
    },
    {
     "round": 60,
     "train": 4.5022,
     "test": 6.1719
    }
   ]
  },
  {
   "maxBin": 64,
   "train": 4.163880535454592,
   "test": 5.720737001017028,
   "gainEvals": 325023,
   "rowTouches": 3369180,
   "histBuilds": 7440,
   "histSubtracts": 7200,
   "nBins": [
    64,
    64,
    64,
    16
   ],
   "curve": [
    {
     "round": 0,
     "train": 13.9026,
     "test": 14.5194
    },
    {
     "round": 1,
     "train": 12.7903,
     "test": 13.4318
    },
    {
     "round": 2,
     "train": 11.8093,
     "test": 12.4809
    },
    {
     "round": 3,
     "train": 10.9296,
     "test": 11.6301
    },
    {
     "round": 4,
     "train": 10.1604,
     "test": 10.8811
    },
    {
     "round": 5,
     "train": 9.4783,
     "test": 10.2364
    },
    {
     "round": 6,
     "train": 8.8682,
     "test": 9.6491
    },
    {
     "round": 7,
     "train": 8.338,
     "test": 9.1506
    },
    {
     "round": 8,
     "train": 7.8758,
     "test": 8.7128
    },
    {
     "round": 9,
     "train": 7.4644,
     "test": 8.3414
    },
    {
     "round": 10,
     "train": 7.1006,
     "test": 8.0018
    },
    {
     "round": 11,
     "train": 6.7792,
     "test": 7.7202
    },
    {
     "round": 12,
     "train": 6.4964,
     "test": 7.4661
    },
    {
     "round": 13,
     "train": 6.2505,
     "test": 7.2502
    },
    {
     "round": 14,
     "train": 6.0314,
     "test": 7.0635
    },
    {
     "round": 15,
     "train": 5.8394,
     "test": 6.8877
    },
    {
     "round": 16,
     "train": 5.6671,
     "test": 6.7463
    },
    {
     "round": 17,
     "train": 5.5212,
     "test": 6.6124
    },
    {
     "round": 18,
     "train": 5.3869,
     "test": 6.5016
    },
    {
     "round": 19,
     "train": 5.2721,
     "test": 6.4073
    },
    {
     "round": 20,
     "train": 5.1674,
     "test": 6.3209
    },
    {
     "round": 21,
     "train": 5.0732,
     "test": 6.2511
    },
    {
     "round": 22,
     "train": 4.9899,
     "test": 6.1737
    },
    {
     "round": 23,
     "train": 4.9214,
     "test": 6.1177
    },
    {
     "round": 24,
     "train": 4.8539,
     "test": 6.0696
    },
    {
     "round": 25,
     "train": 4.7983,
     "test": 6.0224
    },
    {
     "round": 26,
     "train": 4.7468,
     "test": 5.983
    },
    {
     "round": 27,
     "train": 4.6983,
     "test": 5.949
    },
    {
     "round": 28,
     "train": 4.6574,
     "test": 5.9105
    },
    {
     "round": 29,
     "train": 4.6201,
     "test": 5.8853
    },
    {
     "round": 30,
     "train": 4.5869,
     "test": 5.8634
    },
    {
     "round": 31,
     "train": 4.5541,
     "test": 5.8483
    },
    {
     "round": 32,
     "train": 4.5254,
     "test": 5.8282
    },
    {
     "round": 33,
     "train": 4.4947,
     "test": 5.817
    },
    {
     "round": 34,
     "train": 4.4693,
     "test": 5.8008
    },
    {
     "round": 35,
     "train": 4.4479,
     "test": 5.7855
    },
    {
     "round": 36,
     "train": 4.4274,
     "test": 5.779
    },
    {
     "round": 37,
     "train": 4.4095,
     "test": 5.7664
    },
    {
     "round": 38,
     "train": 4.3889,
     "test": 5.7538
    },
    {
     "round": 39,
     "train": 4.3743,
     "test": 5.7498
    },
    {
     "round": 40,
     "train": 4.36,
     "test": 5.744
    },
    {
     "round": 41,
     "train": 4.3461,
     "test": 5.741
    },
    {
     "round": 42,
     "train": 4.3333,
     "test": 5.7395
    },
    {
     "round": 43,
     "train": 4.3196,
     "test": 5.7397
    },
    {
     "round": 44,
     "train": 4.3027,
     "test": 5.7355
    },
    {
     "round": 45,
     "train": 4.2894,
     "test": 5.7357
    },
    {
     "round": 46,
     "train": 4.2782,
     "test": 5.7308
    },
    {
     "round": 47,
     "train": 4.2671,
     "test": 5.729
    },
    {
     "round": 48,
     "train": 4.2575,
     "test": 5.7211
    },
    {
     "round": 49,
     "train": 4.2492,
     "test": 5.722
    },
    {
     "round": 50,
     "train": 4.2396,
     "test": 5.7227
    },
    {
     "round": 51,
     "train": 4.2318,
     "test": 5.7214
    },
    {
     "round": 52,
     "train": 4.223,
     "test": 5.7215
    },
    {
     "round": 53,
     "train": 4.2162,
     "test": 5.7204
    },
    {
     "round": 54,
     "train": 4.209,
     "test": 5.7198
    },
    {
     "round": 55,
     "train": 4.2,
     "test": 5.7235
    },
    {
     "round": 56,
     "train": 4.1941,
     "test": 5.7237
    },
    {
     "round": 57,
     "train": 4.1864,
     "test": 5.7225
    },
    {
     "round": 58,
     "train": 4.182,
     "test": 5.7228
    },
    {
     "round": 59,
     "train": 4.1728,
     "test": 5.7223
    },
    {
     "round": 60,
     "train": 4.1639,
     "test": 5.7207
    }
   ]
  },
  {
   "maxBin": 128,
   "train": 3.910052168551435,
   "test": 5.249605923234877,
   "gainEvals": 648687,
   "rowTouches": 3383744,
   "histBuilds": 7440,
   "histSubtracts": 7200,
   "nBins": [
    128,
    128,
    128,
    16
   ],
   "curve": [
    {
     "round": 0,
     "train": 13.9026,
     "test": 14.5194
    },
    {
     "round": 1,
     "train": 12.7705,
     "test": 13.4126
    },
    {
     "round": 2,
     "train": 11.7688,
     "test": 12.4335
    },
    {
     "round": 3,
     "train": 10.8751,
     "test": 11.5604
    },
    {
     "round": 4,
     "train": 10.0789,
     "test": 10.7892
    },
    {
     "round": 5,
     "train": 9.3751,
     "test": 10.1075
    },
    {
     "round": 6,
     "train": 8.7578,
     "test": 9.5153
    },
    {
     "round": 7,
     "train": 8.2203,
     "test": 9.0098
    },
    {
     "round": 8,
     "train": 7.7413,
     "test": 8.5514
    },
    {
     "round": 9,
     "train": 7.3221,
     "test": 8.1594
    },
    {
     "round": 10,
     "train": 6.9555,
     "test": 7.8118
    },
    {
     "round": 11,
     "train": 6.6288,
     "test": 7.4983
    },
    {
     "round": 12,
     "train": 6.3442,
     "test": 7.2294
    },
    {
     "round": 13,
     "train": 6.0878,
     "test": 6.9922
    },
    {
     "round": 14,
     "train": 5.8559,
     "test": 6.7798
    },
    {
     "round": 15,
     "train": 5.6565,
     "test": 6.6014
    },
    {
     "round": 16,
     "train": 5.4734,
     "test": 6.4353
    },
    {
     "round": 17,
     "train": 5.3211,
     "test": 6.2956
    },
    {
     "round": 18,
     "train": 5.1795,
     "test": 6.1714
    },
    {
     "round": 19,
     "train": 5.0558,
     "test": 6.0591
    },
    {
     "round": 20,
     "train": 4.945,
     "test": 5.966
    },
    {
     "round": 21,
     "train": 4.8429,
     "test": 5.8804
    },
    {
     "round": 22,
     "train": 4.7539,
     "test": 5.8031
    },
    {
     "round": 23,
     "train": 4.6776,
     "test": 5.7435
    },
    {
     "round": 24,
     "train": 4.6111,
     "test": 5.689
    },
    {
     "round": 25,
     "train": 4.5455,
     "test": 5.6395
    },
    {
     "round": 26,
     "train": 4.4897,
     "test": 5.5909
    },
    {
     "round": 27,
     "train": 4.4413,
     "test": 5.5602
    },
    {
     "round": 28,
     "train": 4.3947,
     "test": 5.5226
    },
    {
     "round": 29,
     "train": 4.3547,
     "test": 5.4941
    },
    {
     "round": 30,
     "train": 4.3162,
     "test": 5.4596
    },
    {
     "round": 31,
     "train": 4.285,
     "test": 5.4345
    },
    {
     "round": 32,
     "train": 4.2551,
     "test": 5.4153
    },
    {
     "round": 33,
     "train": 4.2274,
     "test": 5.3901
    },
    {
     "round": 34,
     "train": 4.2038,
     "test": 5.3776
    },
    {
     "round": 35,
     "train": 4.179,
     "test": 5.3672
    },
    {
     "round": 36,
     "train": 4.1603,
     "test": 5.3517
    },
    {
     "round": 37,
     "train": 4.1424,
     "test": 5.3369
    },
    {
     "round": 38,
     "train": 4.1241,
     "test": 5.3281
    },
    {
     "round": 39,
     "train": 4.1069,
     "test": 5.3134
    },
    {
     "round": 40,
     "train": 4.0922,
     "test": 5.307
    },
    {
     "round": 41,
     "train": 4.078,
     "test": 5.3012
    },
    {
     "round": 42,
     "train": 4.065,
     "test": 5.2995
    },
    {
     "round": 43,
     "train": 4.053,
     "test": 5.293
    },
    {
     "round": 44,
     "train": 4.0405,
     "test": 5.2875
    },
    {
     "round": 45,
     "train": 4.0295,
     "test": 5.2825
    },
    {
     "round": 46,
     "train": 4.0196,
     "test": 5.277
    },
    {
     "round": 47,
     "train": 4.0073,
     "test": 5.2706
    },
    {
     "round": 48,
     "train": 3.9987,
     "test": 5.2726
    },
    {
     "round": 49,
     "train": 3.9895,
     "test": 5.2649
    },
    {
     "round": 50,
     "train": 3.9826,
     "test": 5.2639
    },
    {
     "round": 51,
     "train": 3.9731,
     "test": 5.2579
    },
    {
     "round": 52,
     "train": 3.9654,
     "test": 5.257
    },
    {
     "round": 53,
     "train": 3.9562,
     "test": 5.2561
    },
    {
     "round": 54,
     "train": 3.9501,
     "test": 5.2507
    },
    {
     "round": 55,
     "train": 3.9438,
     "test": 5.254
    },
    {
     "round": 56,
     "train": 3.938,
     "test": 5.2517
    },
    {
     "round": 57,
     "train": 3.932,
     "test": 5.2505
    },
    {
     "round": 58,
     "train": 3.9232,
     "test": 5.2511
    },
    {
     "round": 59,
     "train": 3.9167,
     "test": 5.2499
    },
    {
     "round": 60,
     "train": 3.9101,
     "test": 5.2496
    }
   ]
  },
  {
   "maxBin": 255,
   "train": 3.7336419485328847,
   "test": 4.975812636651436,
   "gainEvals": 1262724,
   "rowTouches": 3356816,
   "histBuilds": 7440,
   "histSubtracts": 7200,
   "nBins": [
    255,
    255,
    254,
    16
   ],
   "curve": [
    {
     "round": 0,
     "train": 13.9026,
     "test": 14.5194
    },
    {
     "round": 1,
     "train": 12.7646,
     "test": 13.3989
    },
    {
     "round": 2,
     "train": 11.7548,
     "test": 12.3927
    },
    {
     "round": 3,
     "train": 10.8506,
     "test": 11.5083
    },
    {
     "round": 4,
     "train": 10.0547,
     "test": 10.7282
    },
    {
     "round": 5,
     "train": 9.342,
     "test": 10.03
    },
    {
     "round": 6,
     "train": 8.7155,
     "test": 9.4157
    },
    {
     "round": 7,
     "train": 8.1673,
     "test": 8.8836
    },
    {
     "round": 8,
     "train": 7.679,
     "test": 8.4147
    },
    {
     "round": 9,
     "train": 7.248,
     "test": 7.9961
    },
    {
     "round": 10,
     "train": 6.8562,
     "test": 7.629
    },
    {
     "round": 11,
     "train": 6.5202,
     "test": 7.3142
    },
    {
     "round": 12,
     "train": 6.2186,
     "test": 7.0376
    },
    {
     "round": 13,
     "train": 5.9525,
     "test": 6.7896
    },
    {
     "round": 14,
     "train": 5.7253,
     "test": 6.5851
    },
    {
     "round": 15,
     "train": 5.5147,
     "test": 6.3882
    },
    {
     "round": 16,
     "train": 5.3239,
     "test": 6.2159
    },
    {
     "round": 17,
     "train": 5.165,
     "test": 6.0727
    },
    {
     "round": 18,
     "train": 5.0198,
     "test": 5.943
    },
    {
     "round": 19,
     "train": 4.891,
     "test": 5.8287
    },
    {
     "round": 20,
     "train": 4.7806,
     "test": 5.7318
    },
    {
     "round": 21,
     "train": 4.6787,
     "test": 5.6407
    },
    {
     "round": 22,
     "train": 4.5912,
     "test": 5.5668
    },
    {
     "round": 23,
     "train": 4.507,
     "test": 5.4929
    },
    {
     "round": 24,
     "train": 4.4373,
     "test": 5.431
    },
    {
     "round": 25,
     "train": 4.3718,
     "test": 5.3793
    },
    {
     "round": 26,
     "train": 4.3161,
     "test": 5.3352
    },
    {
     "round": 27,
     "train": 4.2654,
     "test": 5.2905
    },
    {
     "round": 28,
     "train": 4.2187,
     "test": 5.2538
    },
    {
     "round": 29,
     "train": 4.1801,
     "test": 5.2234
    },
    {
     "round": 30,
     "train": 4.1419,
     "test": 5.1991
    },
    {
     "round": 31,
     "train": 4.1059,
     "test": 5.1701
    },
    {
     "round": 32,
     "train": 4.0788,
     "test": 5.1486
    },
    {
     "round": 33,
     "train": 4.0494,
     "test": 5.1246
    },
    {
     "round": 34,
     "train": 4.0258,
     "test": 5.1097
    },
    {
     "round": 35,
     "train": 4.0014,
     "test": 5.0958
    },
    {
     "round": 36,
     "train": 3.9806,
     "test": 5.0801
    },
    {
     "round": 37,
     "train": 3.9625,
     "test": 5.0666
    },
    {
     "round": 38,
     "train": 3.9461,
     "test": 5.0552
    },
    {
     "round": 39,
     "train": 3.9293,
     "test": 5.0484
    },
    {
     "round": 40,
     "train": 3.9153,
     "test": 5.0377
    },
    {
     "round": 41,
     "train": 3.9005,
     "test": 5.0264
    },
    {
     "round": 42,
     "train": 3.8868,
     "test": 5.0179
    },
    {
     "round": 43,
     "train": 3.8758,
     "test": 5.011
    },
    {
     "round": 44,
     "train": 3.8648,
     "test": 5.0031
    },
    {
     "round": 45,
     "train": 3.853,
     "test": 4.9973
    },
    {
     "round": 46,
     "train": 3.8433,
     "test": 4.9963
    },
    {
     "round": 47,
     "train": 3.8323,
     "test": 4.9949
    },
    {
     "round": 48,
     "train": 3.823,
     "test": 4.9905
    },
    {
     "round": 49,
     "train": 3.8145,
     "test": 4.9848
    },
    {
     "round": 50,
     "train": 3.8063,
     "test": 4.9837
    },
    {
     "round": 51,
     "train": 3.7983,
     "test": 4.9793
    },
    {
     "round": 52,
     "train": 3.7892,
     "test": 4.9781
    },
    {
     "round": 53,
     "train": 3.7826,
     "test": 4.9777
    },
    {
     "round": 54,
     "train": 3.7743,
     "test": 4.9781
    },
    {
     "round": 55,
     "train": 3.7668,
     "test": 4.9776
    },
    {
     "round": 56,
     "train": 3.7586,
     "test": 4.9788
    },
    {
     "round": 57,
     "train": 3.7528,
     "test": 4.9756
    },
    {
     "round": 58,
     "train": 3.7453,
     "test": 4.9751
    },
    {
     "round": 59,
     "train": 3.7395,
     "test": 4.9749
    },
    {
     "round": 60,
     "train": 3.7336,
     "test": 4.9758
    }
   ]
  }
 ],
 "leafFloor": [
  {
   "minDataInLeaf": 5,
   "exact": 4.682057140188016,
   "bins": [
    {
     "maxBin": 8,
     "test": 8.008479733742854
    },
    {
     "maxBin": 16,
     "test": 6.862078774702061
    },
    {
     "maxBin": 32,
     "test": 6.235974756402891
    },
    {
     "maxBin": 64,
     "test": 5.716225887153754
    },
    {
     "maxBin": 128,
     "test": 5.27823962741078
    },
    {
     "maxBin": 255,
     "test": 5.039192375498752
    }
   ]
  },
  {
   "minDataInLeaf": 20,
   "exact": 4.957024936342493,
   "bins": [
    {
     "maxBin": 8,
     "test": 7.942572553818205
    },
    {
     "maxBin": 16,
     "test": 6.871619596760051
    },
    {
     "maxBin": 32,
     "test": 6.1718754205546595
    },
    {
     "maxBin": 64,
     "test": 5.720737001017028
    },
    {
     "maxBin": 128,
     "test": 5.249605923234877
    },
    {
     "maxBin": 255,
     "test": 4.975812636651436
    }
   ]
  },
  {
   "minDataInLeaf": 80,
   "exact": 5.502383298367221,
   "bins": [
    {
     "maxBin": 8,
     "test": 7.93128404185968
    },
    {
     "maxBin": 16,
     "test": 6.864442135783439
    },
    {
     "maxBin": 32,
     "test": 6.148145064946285
    },
    {
     "maxBin": 64,
     "test": 5.685459863324354
    },
    {
     "maxBin": 128,
     "test": 5.654189573407315
    },
    {
     "maxBin": 255,
     "test": 5.671021696038952
    }
   ]
  },
  {
   "minDataInLeaf": 250,
   "exact": 6.405227409186093,
   "bins": [
    {
     "maxBin": 8,
     "test": 8.006266198359032
    },
    {
     "maxBin": 16,
     "test": 6.900034836109216
    },
    {
     "maxBin": 32,
     "test": 6.832440434810845
    },
    {
     "maxBin": 64,
     "test": 6.491966364597792
    },
    {
     "maxBin": 128,
     "test": 6.4870704257774925
    },
    {
     "maxBin": 255,
     "test": 6.444584180721081
    }
   ]
  }
 ],
 "needle": {
  "exact": 1.0461049549476662,
  "rows": [
   {
    "maxBin": 2,
    "test": 1.985055353225219,
    "edgesInWindow": 0,
    "nBins": 2
   },
   {
    "maxBin": 4,
    "test": 1.9314383330819043,
    "edgesInWindow": 0,
    "nBins": 4
   },
   {
    "maxBin": 8,
    "test": 1.8177760477853544,
    "edgesInWindow": 0,
    "nBins": 8
   },
   {
    "maxBin": 16,
    "test": 1.7814184303954113,
    "edgesInWindow": 1,
    "nBins": 16
   },
   {
    "maxBin": 32,
    "test": 1.5377830160018813,
    "edgesInWindow": 1,
    "nBins": 32
   },
   {
    "maxBin": 64,
    "test": 1.3719156535557007,
    "edgesInWindow": 2,
    "nBins": 64
   },
   {
    "maxBin": 128,
    "test": 1.0800368072031963,
    "edgesInWindow": 5,
    "nBins": 128
   },
   {
    "maxBin": 255,
    "test": 1.131512744399474,
    "edgesInWindow": 8,
    "nBins": 255
   }
  ]
 },
 "edgeSets": [
  {
   "key": "distance",
   "distinct": 6000,
   "maxTie": 1,
   "edges": {
    "2": 2,
    "4": 4,
    "8": 8,
    "16": 16,
    "32": 32,
    "64": 64,
    "128": 128,
    "255": 255
   }
  },
  {
   "key": "weight",
   "distinct": 6000,
   "maxTie": 1,
   "edges": {
    "2": 2,
    "4": 4,
    "8": 8,
    "16": 16,
    "32": 32,
    "64": 64,
    "128": 128,
    "255": 255
   }
  },
  {
   "key": "hour",
   "distinct": 5779,
   "maxTie": 179,
   "edges": {
    "2": 2,
    "4": 4,
    "8": 8,
    "16": 16,
    "32": 32,
    "64": 64,
    "128": 128,
    "255": 254
   }
  },
  {
   "key": "stops",
   "distinct": 16,
   "maxTie": 1141,
   "edges": {
    "2": 2,
    "4": 4,
    "8": 8,
    "16": 16,
    "32": 16,
    "64": 16,
    "128": 16,
    "255": 16
   }
  }
 ]
};
