/* Generated by scripts/precompute.mjs — do not edit by hand.
   20,000 random technology sets per size, seed 20260913.
   verify/check-numbers.mjs re-runs the simulation and asserts these values. */
export const FREQ_TRIALS = 20000;
export const FREQ_SEED = 20260913;
export const FREQUENCIES = [
  {
    "n": 3,
    "survivors": 36784,
    "never": 1707,
    "shareOfSurvivors": 0.046406046107003045,
    "shareOfSets": 0.08535
  },
  {
    "n": 5,
    "survivors": 45652,
    "never": 4472,
    "shareOfSurvivors": 0.097958468413213,
    "shareOfSets": 0.19265
  },
  {
    "n": 10,
    "survivors": 58522,
    "never": 8718,
    "shareOfSurvivors": 0.14896961826321725,
    "shareOfSets": 0.3298
  },
  {
    "n": 20,
    "survivors": 72001,
    "never": 13228,
    "shareOfSurvivors": 0.1837196705601311,
    "shareOfSets": 0.44965
  },
  {
    "n": 50,
    "survivors": 89764,
    "never": 19307,
    "shareOfSurvivors": 0.21508622610400607,
    "shareOfSets": 0.57565
  }
];
