/*
  Writes src/precomputed.js.

  Only the large-game simulation lives here: 200,000 games at each of seven
  sizes is a second of node and far too much for a page load. The 576-game
  enumeration is NOT precomputed — it is exact, it is instant, and the page
  runs it live so the figure and the check cannot drift apart.
*/
import { writeFileSync } from "node:fs";
import { mulberry32 } from "../src/rng.js";
import { countPureRandom } from "../src/enumerate.js";

const SIZES = [2, 3, 4, 5, 10, 25, 100];
const TRIALS = 200000;
const KMAX = 5;

const rows = SIZES.map((n) => {
  const rand = mulberry32(12345 + n);
  const hist = new Array(KMAX + 1).fill(0);
  let total = 0;
  for (let t = 0; t < TRIALS; t++) {
    const k = countPureRandom(n, rand);
    total += k;
    hist[Math.min(k, KMAX)]++;
  }
  return { n, mean: total / TRIALS, p: hist.map((h) => h / TRIALS) };
});

const body = `/*
  Generated by scripts/precompute.mjs — do not edit by hand.

  ${TRIALS.toLocaleString("en-GB")} random n x n games at each size, seeded with
  mulberry32(12345 + n), counting cells that survive the dots-and-circles test.
  Payoffs are independent uniforms, so ties have probability zero and every
  game is generic.

  \`p[k]\` is the share of games with exactly k pure equilibria, with k = ${KMAX}
  meaning "${KMAX} or more".
*/
export const TRIALS = ${TRIALS};
export const COUNT_BY_SIZE = ${JSON.stringify(rows, null, 2)};
`;

writeFileSync(new URL("../src/precomputed.js", import.meta.url), body);
console.log(`wrote src/precomputed.js — ${rows.length} sizes, ${TRIALS} trials each`);
for (const r of rows) {
  console.log(`  n=${String(r.n).padStart(3)}  mean=${r.mean.toFixed(5)}  P(0)=${r.p[0].toFixed(6)}`);
}
