/*
  Pinned data: download, unzip, hash, parse. Shared by the articles that use
  real data (each article keeps its own copy, so nothing is shared at build
  time). Downloads go through curl, which honours the proxy settings on every
  machine this runs on.
*/
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { inflateRawSync } from "node:zlib";

export const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");

export function download(url) {
  return execFileSync("curl", ["-sSfL", "--max-time", "120", url], { maxBuffer: 64 * 1024 * 1024 });
}

// The first file in a zip archive (French's archives hold one CSV each).
export function unzipFirst(buf) {
  if (buf.readUInt32LE(0) !== 0x04034b50) throw new Error("not a zip archive");
  const method = buf.readUInt16LE(8), csize = buf.readUInt32LE(18), nlen = buf.readUInt16LE(26), xlen = buf.readUInt16LE(28);
  const name = buf.slice(30, 30 + nlen).toString("utf8");
  const start = 30 + nlen + xlen;
  let size = csize;
  if (size === 0) {
    // sizes in a data descriptor: find them from the central directory
    const cd = buf.lastIndexOf(Buffer.from([0x50, 0x4b, 0x01, 0x02]));
    size = buf.readUInt32LE(cd + 20);
  }
  const data = buf.slice(start, start + size);
  return { name, data: method === 0 ? data : inflateRawSync(data) };
}

// One block of a Kenneth French CSV: the first header row (",col,col,…") after
// the first line matching `after`, and the rows of yyyymm or yyyy numbers below
// it, up to the first line that isn't one.
export function frenchBlock(text, after) {
  const lines = text.split(/\r?\n/);
  let i = after ? lines.findIndex((l) => after.test(l)) : 0;
  if (i < 0) throw new Error("block not found: " + after);
  let h = i; while (h < lines.length && !/^\s*,/.test(lines[h])) h++;
  const cols = lines[h].split(",").slice(1).map((s) => s.trim());
  const rows = [];
  for (let k = h + 1; k < lines.length; k++) {
    const l = lines[k];
    if (!/^\s*\d{4,6}\s*,/.test(l)) break;
    const p = l.split(",").map((s) => s.trim());
    rows.push([+p[0], ...p.slice(1).map(Number)]);
  }
  return { cols, rows };
}

// Write a JS module of plain data, stable across runs (no timestamps).
export function jsModule(comment, obj) {
  return `/*\n  ${comment.split("\n").join("\n  ")}\n\n  Generated by scripts/build-data.mjs from the pinned files in data/. Do not\n  edit by hand: run \`node scripts/build-data.mjs\`.\n*/\nexport default ${JSON.stringify(obj)};\n`;
}
