/*
  The curves the page draws, from the same module the page imports, written
  to src/precomputed.js. Each takes thousands of eigenfunction sums, too slow
  for page load; the first check in check-numbers.mjs runs this again and
  compares. Depths are in log points (a fall of 1 − e^(−d) in money).
*/
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { median, quantile, cdf, density, logOf, SIGMA } from "../src/drawdown.js";

const r6 = (x) => +x.toPrecision(6);
const logGrid = (a, b, n) => Array.from({ length: n }, (_, i) => a * Math.pow(b / a, i / (n - 1)));

export function run() {
  const YEARS = logGrid(0.25, 100, 61).map(r6);
  const SRS = [0, 0.25, 0.5, 1];
  const MEDIANS = Object.fromEntries(SRS.map((sr) => [sr, YEARS.map((T) => r6(median(sr * SIGMA, SIGMA, T)))]));
  const TAUS = logGrid(0.01, 1000, 81).map(r6);
  const MASTER = TAUS.map((t) => r6(quantile(0.5, 1, 1, t)));
  // the chance that L live years beat the worst drawdown of B backtest years,
  // as one dot product per pair on a shared grid of depths
  const LIVE = Array.from({ length: 80 }, (_, i) => (i + 1) / 2);
  const BACK = [5, 10, 20];
  const BEAT = {};
  for (const sr of [0.5, 0]) {
    const mu = sr * SIGMA, n = 1600, H = 1.25 * quantile(0.99999, mu, SIGMA, 40), dh = H / n;
    const mid = Array.from({ length: n }, (_, i) => (i + 0.5) * dh);
    const over = Object.fromEntries(LIVE.map((L) => [L, mid.map((h) => 1 - cdf(h, mu, SIGMA, L))]));
    BEAT[sr] = {};
    for (const B of BACK) {
      const F = Array.from({ length: n + 1 }, (_, i) => (i ? cdf(i * dh, mu, SIGMA, B) : 0));
      BEAT[sr][B] = LIVE.map((L) => { let a = 0; for (let i = 0; i < n; i++) a += (F[i + 1] - F[i]) * over[L][i]; return r6(a); });
    }
  }
  // densities of the worst drawdown, for the detection figure
  const DMAX = r6(logOf(0.85));
  const DENS = {};
  for (const T of [2, 5, 10]) DENS[T] = Object.fromEntries([0.5, 0].map((sr) => [sr, density(sr * SIGMA, SIGMA, T, 0, DMAX, 120).map(([, f]) => r6(f))]));
  const out = { YEARS, MEDIANS, TAUS, MASTER, LIVE, BACK, BEAT, DMAX, DENS };
  return "/*\n  Generated by scripts/precompute.mjs from src/drawdown.js. Do not edit by hand:\n  run `npm run precompute`.\n*/\nexport default " + JSON.stringify(out) + ";\n";
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(new URL("../src/precomputed.js", import.meta.url), run());
  console.log("wrote src/precomputed.js");
}
