/*
  Generates src/precomputed.js.

      node scripts/precompute.mjs

  Why this exists. Every other article in this project computes its figures in
  the browser on page load, so the prose cannot drift from the code. Here that
  costs about a second of blocking JavaScript - eight boosted forests for the
  bin sweep, four more for the leaf-floor grid, and an exact-split model that is
  three times the work of any of them - which would leave the page blank while
  it ran.

  So the sweeps are computed here instead, by the SAME modules the page imports,
  and written out as data. The guarantee is preserved by verify/check-numbers.mjs,
  which re-runs every one of these fits and fails if the committed numbers have
  moved. A stale precompute is a failing check, not a silent lie.
*/
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { TRAIN_COLS, TRAIN_Y, TEST_COLS, TEST_Y, FEATURES, N_TRAIN, N_TEST,
         NEEDLE_TRAIN, NEEDLE_TEST, NEEDLE_LO, NEEDLE_HI, column, targets } from "../src/datasets.js";
import { fit, DEFAULTS } from "../src/gbdt.js";
import { binEdges } from "../src/binning.js";

export const BIN_SETTINGS = [2, 4, 8, 16, 32, 64, 128, 255];
export const LEAF_FLOORS = [5, 20, 80, 250];
export const FLOOR_BINS = [8, 16, 32, 64, 128, 255];

const slim = (m) => ({
  train: m.train,
  test: m.test,
  gainEvals: m.counters.gainEvals,
  rowTouches: m.counters.rowTouches,
  histBuilds: m.counters.histBuilds,
  histSubtracts: m.counters.histSubtracts,
  nBins: m.nBins,
  curve: m.curve.map((c) => ({ round: c.round, train: +c.train.toFixed(4), test: +c.test.toFixed(4) })),
});

export function computeAll(log = () => {}) {
  const out = { config: { N_TRAIN, N_TEST, ...DEFAULTS }, BIN_SETTINGS, LEAF_FLOORS, FLOOR_BINS };

  log("comparison");
  out.exact = slim(fit(TRAIN_COLS, TRAIN_Y, TEST_COLS, TEST_Y, { mode: "exact" }));
  out.hist = slim(fit(TRAIN_COLS, TRAIN_Y, TEST_COLS, TEST_Y, { mode: "hist", maxBin: 255 }));
  out.histNoSubtract = slim(fit(TRAIN_COLS, TRAIN_Y, TEST_COLS, TEST_Y, { mode: "hist", maxBin: 255, subtract: false }));

  log("split trace");
  const splits = [];
  fit(TRAIN_COLS, TRAIN_Y, null, null, {
    mode: "hist", maxBin: 255, numTrees: 1, onSplit: (s) => splits.push(s),
  });
  out.splitTrace = splits;

  log("bin sweep");
  out.binSweep = BIN_SETTINGS.map((maxBin) => ({
    maxBin,
    ...slim(fit(TRAIN_COLS, TRAIN_Y, TEST_COLS, TEST_Y, { mode: "hist", maxBin })),
  }));

  log("leaf-floor grid");
  out.leafFloor = LEAF_FLOORS.map((minDataInLeaf) => ({
    minDataInLeaf,
    exact: fit(TRAIN_COLS, TRAIN_Y, TEST_COLS, TEST_Y, { mode: "exact", minDataInLeaf }).test,
    bins: FLOOR_BINS.map((maxBin) => ({
      maxBin,
      test: fit(TRAIN_COLS, TRAIN_Y, TEST_COLS, TEST_Y, { mode: "hist", maxBin, minDataInLeaf }).test,
    })),
  }));

  log("needle");
  const ncols = [column(NEEDLE_TRAIN, 0)];
  const ny = targets(NEEDLE_TRAIN);
  const ntc = [column(NEEDLE_TEST, 0)];
  const nty = targets(NEEDLE_TEST);
  const needleOpts = { numTrees: 40, numLeaves: 15 };
  out.needle = {
    exact: fit(ncols, ny, ntc, nty, { mode: "exact", ...needleOpts }).test,
    rows: BIN_SETTINGS.map((maxBin) => {
      const edges = binEdges(ncols[0], maxBin, {});
      return {
        maxBin,
        test: fit(ncols, ny, ntc, nty, { mode: "hist", maxBin, ...needleOpts }).test,
        edgesInWindow: edges.filter((v) => v >= NEEDLE_LO && v < NEEDLE_HI).length,
        nBins: edges.length + 1,
      };
    }),
  };

  log("bin edges for the figures");
  out.edgeSets = FEATURES.map((f, j) => {
    // The largest group of identical values. A value held by more rows than a
    // bin's share cannot be split across two bins, so it swallows a boundary
    // and the realised bin count comes out below max_bin.
    const tally = new Map();
    for (const v of TRAIN_COLS[j]) tally.set(v, (tally.get(v) || 0) + 1);
    return {
      key: f.key,
      distinct: tally.size,
      maxTie: Math.max(...tally.values()),
      edges: Object.fromEntries(BIN_SETTINGS.map((b) => [b, binEdges(TRAIN_COLS[j], b, {}).length + 1])),
    };
  });

  return out;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const t0 = Date.now();
  const data = computeAll((s) => process.stdout.write("  " + s + "\n"));
  const here = dirname(fileURLToPath(import.meta.url));
  const body =
    "/*\n" +
    "  GENERATED by scripts/precompute.mjs - do not edit.\n\n" +
    "  Produced by the same modules the page imports (src/gbdt.js, src/binning.js,\n" +
    "  src/datasets.js). verify/check-numbers.mjs re-runs every fit in here and\n" +
    "  fails if any number has moved, so this file cannot go stale unnoticed.\n" +
    "*/\n" +
    "export default " + JSON.stringify(data, null, 1) + ";\n";
  writeFileSync(join(here, "../src/precomputed.js"), body);
  console.log("wrote src/precomputed.js in " + ((Date.now() - t0) / 1000).toFixed(1) + "s, " +
              (body.length / 1024).toFixed(0) + " KB");
}
