/*
  How often the rectangle test is not enough.

  Scatter n technologies uniformly in the unit input box and ask two questions:
  how many survive the dominance test, and how many of THOSE are the cheapest
  choice at no relative price at all. Seeded, so `npm run check` re-derives every
  number in src/precomputed.js rather than trusting it.

  Uniform scatter is a null model, not a claim about real technology menus — the
  article says so. Its job is to show that the gap is a generic feature of a set
  of points and not an artefact of the seven this article draws.
*/
import { writeFileSync } from "node:fs";
import { undominated, isEverChosen } from "../src/technology.js";

export function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export const SIZES = [3, 5, 10, 20, 50];
export const TRIALS = 20000;
export const SEED = 20260913;

export function frequencies() {
  const rows = [];
  for (const n of SIZES) {
    const rnd = mulberry32(SEED + n);
    let survivors = 0, never = 0, setsWithOne = 0;
    for (let i = 0; i < TRIALS; i++) {
      const s = [];
      for (let j = 0; j < n; j++) s.push({ id: j, N: rnd() * 10, R: rnd() * 10 });
      let any = false;
      for (const t of undominated(s)) {
        survivors++;
        if (!isEverChosen(t, s)) { never++; any = true; }
      }
      if (any) setsWithOne++;
    }
    rows.push({
      n,
      survivors,
      never,
      shareOfSurvivors: never / survivors,
      shareOfSets: setsWithOne / TRIALS,
    });
  }
  return rows;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const rows = frequencies();
  const body =
`/* Generated by scripts/precompute.mjs — do not edit by hand.
   ${TRIALS.toLocaleString("en-GB")} random technology sets per size, seed ${SEED}.
   verify/check-numbers.mjs re-runs the simulation and asserts these values. */
export const FREQ_TRIALS = ${TRIALS};
export const FREQ_SEED = ${SEED};
export const FREQUENCIES = ${JSON.stringify(rows, null, 2)};
`;
  writeFileSync(new URL("../src/precomputed.js", import.meta.url), body);
  for (const r of rows) {
    console.log(
      `n=${String(r.n).padStart(2)}  survivors ${String(r.survivors).padStart(7)}` +
      `  never chosen ${String(r.never).padStart(6)} (${(100 * r.shareOfSurvivors).toFixed(1)}%)` +
      `  sets with one: ${(100 * r.shareOfSets).toFixed(1)}%`
    );
  }
}
